<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Artisan;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        Artisan::call('module:seed');
        $this->call(ActivityLogTableSeeder::class);
        $this->call(AssetsTableSeeder::class);
        $this->call(AssetDepreciationTableSeeder::class);
        $this->call(AssetFilesTableSeeder::class);
        $this->call(AssetMaintenanceTableSeeder::class);
        $this->call(AssetMaintenanceTypesTableSeeder::class);
        $this->call(AssetNotesTableSeeder::class);
        $this->call(AssetPicturesTableSeeder::class);
        $this->call(AssetTypesTableSeeder::class);
        $this->call(BranchesTableSeeder::class);
        $this->call(BranchUsersTableSeeder::class);
        $this->call(ChartOfAccountsTableSeeder::class);
        $this->call(ClientsTableSeeder::class);
        $this->call(ClientFilesTableSeeder::class);
        $this->call(ClientFileTypesTableSeeder::class);
        $this->call(ClientIdentificationTableSeeder::class);
        $this->call(ClientIdentificationTypesTableSeeder::class);
        $this->call(ClientNextOfKinTableSeeder::class);
        $this->call(ClientRelationshipsTableSeeder::class);
        $this->call(ClientTypesTableSeeder::class);
        $this->call(ClientUsersTableSeeder::class);
        $this->call(CommunicationCampaignsTableSeeder::class);
        $this->call(CommunicationCampaignAttachmentTypesTableSeeder::class);
        $this->call(CommunicationCampaignBusinessRulesTableSeeder::class);
        $this->call(CommunicationCampaignLogsTableSeeder::class);
        $this->call(CountriesTableSeeder::class);
        $this->call(CurrenciesTableSeeder::class);
        $this->call(CustomFieldsTableSeeder::class);
        $this->call(CustomFieldsMetaTableSeeder::class);
        $this->call(ExpensesTableSeeder::class);
        $this->call(ExpenseTypesTableSeeder::class);
        $this->call(FailedJobsTableSeeder::class);
        $this->call(FundsTableSeeder::class);
        $this->call(IncomeTableSeeder::class);
        $this->call(IncomeTypesTableSeeder::class);
        $this->call(JobsTableSeeder::class);
        $this->call(JournalEntriesTableSeeder::class);
        $this->call(LoansTableSeeder::class);
        $this->call(LoanApplicationsTableSeeder::class);
        $this->call(LoanChargesTableSeeder::class);
        $this->call(LoanChargeOptionsTableSeeder::class);
        $this->call(LoanChargeTypesTableSeeder::class);
        $this->call(LoanCollateralTableSeeder::class);
        $this->call(LoanCollateralTypesTableSeeder::class);
        $this->call(LoanCreditChecksTableSeeder::class);
        $this->call(LoanDisbursementChannelsTableSeeder::class);
        $this->call(LoanFilesTableSeeder::class);
        $this->call(LoanFileTypesTableSeeder::class);
        $this->call(LoanGuarantorsTableSeeder::class);
        $this->call(LoanHistoryTableSeeder::class);
        $this->call(LoanLinkedChargesTableSeeder::class);
        $this->call(LoanLinkedCreditChecksTableSeeder::class);
        $this->call(LoanNotesTableSeeder::class);
        $this->call(LoanOfficerHistoryTableSeeder::class);
        $this->call(LoanProductsTableSeeder::class);
        $this->call(LoanProductLinkedChargesTableSeeder::class);
        $this->call(LoanProductLinkedCreditChecksTableSeeder::class);
        $this->call(LoanProvisioningTableSeeder::class);
        $this->call(LoanPurposesTableSeeder::class);
        $this->call(LoanRepaymentSchedulesTableSeeder::class);
        $this->call(LoanTransactionsTableSeeder::class);
        $this->call(LoanTransactionProcessingStrategiesTableSeeder::class);
        $this->call(LoanTransactionTypesTableSeeder::class);
        $this->call(MenusTableSeeder::class);
        $this->call(MigrationsTableSeeder::class);
        $this->call(ModelHasPermissionsTableSeeder::class);
        $this->call(ModelHasRolesTableSeeder::class);
        $this->call(NotificationsTableSeeder::class);
        $this->call(OauthAccessTokensTableSeeder::class);
        $this->call(OauthAuthCodesTableSeeder::class);
        $this->call(OauthClientsTableSeeder::class);
        $this->call(OauthPersonalAccessClientsTableSeeder::class);
        $this->call(OauthRefreshTokensTableSeeder::class);
        $this->call(PasswordResetsTableSeeder::class);
        $this->call(PaymentDetailsTableSeeder::class);
        $this->call(PaymentTypesTableSeeder::class);
        $this->call(PayrollTableSeeder::class);
        $this->call(PayrollItemsTableSeeder::class);
        $this->call(PayrollItemsMetaTableSeeder::class);
        $this->call(PayrollPaymentsTableSeeder::class);
        $this->call(PayrollTemplatesTableSeeder::class);
        $this->call(PayrollTemplateItemsTableSeeder::class);
        $this->call(PermissionsTableSeeder::class);
        $this->call(ProfessionsTableSeeder::class);
        $this->call(RolesTableSeeder::class);
        $this->call(RoleHasPermissionsTableSeeder::class);
        $this->call(SavingsTableSeeder::class);
        $this->call(SavingsChargesTableSeeder::class);
        $this->call(SavingsChargeOptionsTableSeeder::class);
        $this->call(SavingsChargeTypesTableSeeder::class);
        $this->call(SavingsFilesTableSeeder::class);
        $this->call(SavingsFileTypesTableSeeder::class);
        $this->call(SavingsLinkedChargesTableSeeder::class);
        $this->call(SavingsProductsTableSeeder::class);
        $this->call(SavingsProductLinkedChargesTableSeeder::class);
        $this->call(SavingsTransactionsTableSeeder::class);
        $this->call(SavingsTransactionTypesTableSeeder::class);
        $this->call(SettingsTableSeeder::class);
        $this->call(SharesTableSeeder::class);
        $this->call(ShareChargesTableSeeder::class);
        $this->call(ShareChargeOptionsTableSeeder::class);
        $this->call(ShareChargeTypesTableSeeder::class);
        $this->call(ShareLinkedChargesTableSeeder::class);
        $this->call(ShareMarketPeriodsTableSeeder::class);
        $this->call(ShareProductsTableSeeder::class);
        $this->call(ShareProductLinkedChargesTableSeeder::class);
        $this->call(ShareTransactionsTableSeeder::class);
        $this->call(ShareTransactionTypesTableSeeder::class);
        $this->call(SmsGatewaysTableSeeder::class);
        $this->call(TaxRatesTableSeeder::class);
        $this->call(TelescopeEntriesTableSeeder::class);
        $this->call(TelescopeEntriesTagsTableSeeder::class);
        $this->call(TelescopeMonitoringTableSeeder::class);
        $this->call(TimezonesTableSeeder::class);
        $this->call(TitlesTableSeeder::class);
        $this->call(UsersTableSeeder::class);
        $this->call(WalletsTableSeeder::class);
        $this->call(WalletTransactionsTableSeeder::class);
        $this->call(WidgetsTableSeeder::class);
    }
}
