<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenusTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menus')->delete();
        
        \DB::table('menus')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_id' => NULL,
                'parent_id' => NULL,
                'parent_slug' => '',
                'is_parent' => 1,
                'name' => 'Settings',
                'title' => NULL,
                'slug' => 'settings',
                'description' => NULL,
                'menu_order' => 31,
                'url' => 'setting',
                'permissions' => 'setting.setting.index',
                'icon' => 'fas fa-cogs',
                'module' => 'Setting',
                'created_at' => '2023-11-08 17:34:44',
                'updated_at' => '2023-11-08 17:34:44',
            ),
            1 => 
            array (
                'id' => 2,
                'menu_id' => NULL,
                'parent_id' => 1,
                'parent_slug' => 'settings',
                'is_parent' => 0,
                'name' => 'Organisation Settings',
                'title' => NULL,
                'slug' => 'organisation_settings',
                'description' => NULL,
                'menu_order' => 32,
                'url' => 'setting/organisation',
                'permissions' => 'setting.setting.index',
                'icon' => 'far fa-circle',
                'module' => 'Setting',
                'created_at' => '2023-11-08 17:34:44',
                'updated_at' => '2023-11-08 17:34:44',
            ),
            2 => 
            array (
                'id' => 3,
                'menu_id' => NULL,
                'parent_id' => 1,
                'parent_slug' => 'settings',
                'is_parent' => 0,
                'name' => 'General Settings',
                'title' => NULL,
                'slug' => 'general_settings',
                'description' => NULL,
                'menu_order' => 33,
                'url' => 'setting/general',
                'permissions' => 'setting.setting.index',
                'icon' => 'far fa-circle',
                'module' => 'Setting',
                'created_at' => '2023-11-08 17:34:44',
                'updated_at' => '2023-11-08 17:34:44',
            ),
            3 => 
            array (
                'id' => 4,
                'menu_id' => NULL,
                'parent_id' => 1,
                'parent_slug' => 'settings',
                'is_parent' => 0,
                'name' => 'Email Settings',
                'title' => NULL,
                'slug' => 'email_settings',
                'description' => NULL,
                'menu_order' => 34,
                'url' => 'setting/email',
                'permissions' => 'setting.setting.index',
                'icon' => 'far fa-circle',
                'module' => 'Setting',
                'created_at' => '2023-11-08 17:34:44',
                'updated_at' => '2023-11-08 17:34:44',
            ),
            4 => 
            array (
                'id' => 5,
                'menu_id' => NULL,
                'parent_id' => 1,
                'parent_slug' => 'settings',
                'is_parent' => 0,
                'name' => 'SMS Settings',
                'title' => NULL,
                'slug' => 'sms_settings',
                'description' => NULL,
                'menu_order' => 35,
                'url' => 'setting/sms',
                'permissions' => 'setting.setting.index',
                'icon' => 'far fa-circle',
                'module' => 'Setting',
                'created_at' => '2023-11-08 17:34:44',
                'updated_at' => '2023-11-08 17:34:44',
            ),
            5 => 
            array (
                'id' => 6,
                'menu_id' => NULL,
                'parent_id' => 1,
                'parent_slug' => 'settings',
                'is_parent' => 0,
                'name' => 'System Settings',
                'title' => NULL,
                'slug' => 'system_settings',
                'description' => NULL,
                'menu_order' => 36,
                'url' => 'setting/system',
                'permissions' => 'setting.setting.index',
                'icon' => 'far fa-circle',
                'module' => 'Setting',
                'created_at' => '2023-11-08 17:34:44',
                'updated_at' => '2023-11-08 17:34:44',
            ),
            6 => 
            array (
                'id' => 7,
                'menu_id' => NULL,
                'parent_id' => 1,
                'parent_slug' => 'settings',
                'is_parent' => 0,
                'name' => 'System Update',
                'title' => NULL,
                'slug' => 'system_update',
                'description' => NULL,
                'menu_order' => 37,
                'url' => 'setting/system_update',
                'permissions' => 'setting.setting.index',
                'icon' => 'far fa-circle',
                'module' => 'Setting',
                'created_at' => '2023-11-08 17:34:44',
                'updated_at' => '2023-11-08 17:34:44',
            ),
            7 => 
            array (
                'id' => 8,
                'menu_id' => NULL,
                'parent_id' => 1,
                'parent_slug' => 'settings',
                'is_parent' => 0,
                'name' => 'Other Settings',
                'title' => NULL,
                'slug' => 'other_settings',
                'description' => NULL,
                'menu_order' => 38,
                'url' => 'setting/other',
                'permissions' => 'setting.setting.index',
                'icon' => 'far fa-circle',
                'module' => 'Setting',
                'created_at' => '2023-11-08 17:34:44',
                'updated_at' => '2023-11-08 17:34:44',
            ),
            8 => 
            array (
                'id' => 9,
                'menu_id' => NULL,
                'parent_id' => NULL,
                'parent_slug' => '',
                'is_parent' => 1,
                'name' => 'Manage Modules',
                'title' => NULL,
                'slug' => 'modules',
                'description' => NULL,
                'menu_order' => 30,
                'url' => 'module',
                'permissions' => 'core.modules.index',
                'icon' => 'fas fa-plug',
                'module' => 'Core',
                'created_at' => '2023-11-08 17:34:44',
                'updated_at' => '2023-11-08 17:34:44',
            ),
            9 => 
            array (
                'id' => 10,
                'menu_id' => NULL,
                'parent_id' => NULL,
                'parent_slug' => '',
                'is_parent' => 1,
                'name' => 'Manage Menu',
                'title' => NULL,
                'slug' => 'menu',
                'description' => NULL,
                'menu_order' => 31,
                'url' => 'menu',
                'permissions' => 'core.menu.index',
                'icon' => 'fas fa-bars',
                'module' => 'Core',
                'created_at' => '2023-11-08 17:34:44',
                'updated_at' => '2023-11-08 17:34:44',
            ),
            10 => 
            array (
                'id' => 11,
                'menu_id' => NULL,
                'parent_id' => 1,
                'parent_slug' => 'settings',
                'is_parent' => 0,
                'name' => 'Payment Gateways',
                'title' => NULL,
                'slug' => 'menu',
                'description' => NULL,
                'menu_order' => 32,
                'url' => 'settings/payment_gateway',
                'permissions' => 'core.payment_gateways.index',
                'icon' => 'fas fa-money-bill',
                'module' => 'Core',
                'created_at' => '2023-11-08 17:34:44',
                'updated_at' => '2023-11-08 17:34:44',
            ),
            11 => 
            array (
                'id' => 12,
                'menu_id' => NULL,
                'parent_id' => NULL,
                'parent_slug' => '',
                'is_parent' => 1,
                'name' => 'Themes',
                'title' => NULL,
                'slug' => 'themes',
                'description' => NULL,
                'menu_order' => 40,
                'url' => 'theme',
                'permissions' => 'core.themes.index',
                'icon' => 'fas fa-palette',
                'module' => 'Core',
                'created_at' => '2023-11-08 17:34:44',
                'updated_at' => '2023-11-08 17:34:44',
            ),
            12 => 
            array (
                'id' => 13,
                'menu_id' => NULL,
                'parent_id' => NULL,
                'parent_slug' => '',
                'is_parent' => 1,
                'name' => 'Users',
                'title' => NULL,
                'slug' => 'users',
                'description' => NULL,
                'menu_order' => 27,
                'url' => 'user',
                'permissions' => '',
                'icon' => 'fas fa-users',
                'module' => 'User',
                'created_at' => '2023-11-08 17:34:44',
                'updated_at' => '2023-11-08 17:34:44',
            ),
            13 => 
            array (
                'id' => 14,
                'menu_id' => NULL,
                'parent_id' => 13,
                'parent_slug' => 'users',
                'is_parent' => 0,
                'name' => 'View Users',
                'title' => NULL,
                'slug' => 'view_loans',
                'description' => NULL,
                'menu_order' => 28,
                'url' => 'user',
                'permissions' => 'user.users.index',
                'icon' => 'far fa-circle',
                'module' => 'User',
                'created_at' => '2023-11-08 17:34:44',
                'updated_at' => '2023-11-08 17:34:44',
            ),
            14 => 
            array (
                'id' => 15,
                'menu_id' => NULL,
                'parent_id' => 13,
                'parent_slug' => 'users',
                'is_parent' => 0,
                'name' => 'Create User',
                'title' => NULL,
                'slug' => 'create_loan',
                'description' => NULL,
                'menu_order' => 29,
                'url' => 'user/create',
                'permissions' => 'user.users.create',
                'icon' => 'far fa-circle',
                'module' => 'User',
                'created_at' => '2023-11-08 17:34:44',
                'updated_at' => '2023-11-08 17:34:44',
            ),
            15 => 
            array (
                'id' => 16,
                'menu_id' => NULL,
                'parent_id' => 13,
                'parent_slug' => 'users',
                'is_parent' => 0,
                'name' => 'Manage Roles',
                'title' => NULL,
                'slug' => 'manage_roles',
                'description' => NULL,
                'menu_order' => 30,
                'url' => 'user/role',
                'permissions' => 'user.roles.index',
                'icon' => 'far fa-circle',
                'module' => 'User',
                'created_at' => '2023-11-08 17:34:44',
                'updated_at' => '2023-11-08 17:34:44',
            ),
            16 => 
            array (
                'id' => 17,
                'menu_id' => NULL,
                'parent_id' => NULL,
                'parent_slug' => '',
                'is_parent' => 1,
                'name' => 'Dashboard',
                'title' => NULL,
                'slug' => 'dashboard',
                'description' => NULL,
                'menu_order' => 0,
                'url' => 'dashboard',
                'permissions' => 'dashboard.index',
                'icon' => 'fas fa-home',
                'module' => 'Dashboard',
                'created_at' => '2023-11-08 17:34:44',
                'updated_at' => '2023-11-08 17:34:44',
            ),
            17 => 
            array (
                'id' => 18,
                'menu_id' => NULL,
                'parent_id' => NULL,
                'parent_slug' => '',
                'is_parent' => 1,
                'name' => 'Branches',
                'title' => NULL,
                'slug' => 'branches',
                'description' => NULL,
                'menu_order' => 6,
                'url' => 'branch',
                'permissions' => '',
                'icon' => 'fas fa-building',
                'module' => 'Branch',
                'created_at' => '2023-11-08 17:34:44',
                'updated_at' => '2023-11-08 17:34:44',
            ),
            18 => 
            array (
                'id' => 19,
                'menu_id' => NULL,
                'parent_id' => 18,
                'parent_slug' => 'branches',
                'is_parent' => 0,
                'name' => 'View Branches',
                'title' => NULL,
                'slug' => 'view_branches',
                'description' => NULL,
                'menu_order' => 7,
                'url' => 'branch',
                'permissions' => 'branch.branches.index',
                'icon' => 'far fa-circle',
                'module' => 'Branch',
                'created_at' => '2023-11-08 17:34:44',
                'updated_at' => '2023-11-08 17:34:44',
            ),
            19 => 
            array (
                'id' => 20,
                'menu_id' => NULL,
                'parent_id' => 18,
                'parent_slug' => 'branches',
                'is_parent' => 0,
                'name' => 'Create Branch',
                'title' => NULL,
                'slug' => 'create_branch',
                'description' => NULL,
                'menu_order' => 8,
                'url' => 'branch/create',
                'permissions' => 'branch.branches.create',
                'icon' => 'far fa-circle',
                'module' => 'Branch',
                'created_at' => '2023-11-08 17:34:44',
                'updated_at' => '2023-11-08 17:34:44',
            ),
            20 => 
            array (
                'id' => 21,
                'menu_id' => NULL,
                'parent_id' => NULL,
                'parent_slug' => '',
                'is_parent' => 1,
                'name' => 'Accounting',
                'title' => NULL,
                'slug' => 'accounting',
                'description' => NULL,
                'menu_order' => 3,
                'url' => 'accounting',
                'permissions' => '',
                'icon' => 'fas fa-money-bill',
                'module' => 'Accounting',
                'created_at' => '2023-11-08 17:34:44',
                'updated_at' => '2023-11-08 17:34:44',
            ),
            21 => 
            array (
                'id' => 22,
                'menu_id' => NULL,
                'parent_id' => 21,
                'parent_slug' => 'accounting',
                'is_parent' => 0,
                'name' => 'View Charts of Accounts',
                'title' => NULL,
                'slug' => 'view_charts_of_accounts',
                'description' => NULL,
                'menu_order' => 4,
                'url' => 'accounting/chart_of_account',
                'permissions' => 'accounting.chart_of_accounts.index',
                'icon' => 'far fa-circle',
                'module' => 'Accounting',
                'created_at' => '2023-11-08 17:34:44',
                'updated_at' => '2023-11-08 17:34:44',
            ),
            22 => 
            array (
                'id' => 23,
                'menu_id' => NULL,
                'parent_id' => 21,
                'parent_slug' => 'accounting',
                'is_parent' => 0,
                'name' => 'Journal Entries',
                'title' => NULL,
                'slug' => 'journal_entries',
                'description' => NULL,
                'menu_order' => 5,
                'url' => 'accounting/journal_entry',
                'permissions' => 'accounting.journal_entries.index',
                'icon' => 'far fa-circle',
                'module' => 'Accounting',
                'created_at' => '2023-11-08 17:34:44',
                'updated_at' => '2023-11-08 17:34:44',
            ),
            23 => 
            array (
                'id' => 24,
                'menu_id' => NULL,
                'parent_id' => NULL,
                'parent_slug' => '',
                'is_parent' => 1,
                'name' => 'Assets',
                'title' => NULL,
                'slug' => 'assets',
                'description' => NULL,
                'menu_order' => 30,
                'url' => 'asset',
                'permissions' => 'asset.assets.index',
                'icon' => 'fas fa-building',
                'module' => 'Asset',
                'created_at' => '2023-11-08 17:34:45',
                'updated_at' => '2023-11-08 17:34:45',
            ),
            24 => 
            array (
                'id' => 25,
                'menu_id' => NULL,
                'parent_id' => 24,
                'parent_slug' => 'assets',
                'is_parent' => 0,
                'name' => 'View Assets',
                'title' => NULL,
                'slug' => 'view_assets',
                'description' => NULL,
                'menu_order' => 7,
                'url' => 'asset',
                'permissions' => 'asset.assets.index',
                'icon' => 'far fa-circle',
                'module' => 'Asset',
                'created_at' => '2023-11-08 17:34:45',
                'updated_at' => '2023-11-08 17:34:45',
            ),
            25 => 
            array (
                'id' => 26,
                'menu_id' => NULL,
                'parent_id' => 24,
                'parent_slug' => 'assets',
                'is_parent' => 0,
                'name' => 'Create Asset',
                'title' => NULL,
                'slug' => 'create_asset',
                'description' => NULL,
                'menu_order' => 8,
                'url' => 'asset/create',
                'permissions' => 'asset.assets.create',
                'icon' => 'far fa-circle',
                'module' => 'Asset',
                'created_at' => '2023-11-08 17:34:45',
                'updated_at' => '2023-11-08 17:34:45',
            ),
            26 => 
            array (
                'id' => 27,
                'menu_id' => NULL,
                'parent_id' => 24,
                'parent_slug' => 'assets',
                'is_parent' => 0,
                'name' => 'Manage Asset Types',
                'title' => NULL,
                'slug' => 'manage_asset_types',
                'description' => NULL,
                'menu_order' => 9,
                'url' => 'asset/type',
                'permissions' => 'asset.assets.types.index',
                'icon' => 'far fa-circle',
                'module' => 'Asset',
                'created_at' => '2023-11-08 17:34:45',
                'updated_at' => '2023-11-08 17:34:45',
            ),
            27 => 
            array (
                'id' => 28,
                'menu_id' => NULL,
                'parent_id' => NULL,
                'parent_slug' => '',
                'is_parent' => 1,
                'name' => 'Clients',
                'title' => NULL,
                'slug' => 'clients',
                'description' => NULL,
                'menu_order' => 10,
                'url' => 'client',
                'permissions' => '',
                'icon' => 'fas fa-users',
                'module' => 'Client',
                'created_at' => '2023-11-08 17:34:46',
                'updated_at' => '2023-11-08 17:34:46',
            ),
            28 => 
            array (
                'id' => 29,
                'menu_id' => NULL,
                'parent_id' => 28,
                'parent_slug' => 'clients',
                'is_parent' => 0,
                'name' => 'View Clients',
                'title' => NULL,
                'slug' => 'view_clients',
                'description' => NULL,
                'menu_order' => 11,
                'url' => 'client',
                'permissions' => 'client.clients.index',
                'icon' => 'far fa-circle',
                'module' => 'Client',
                'created_at' => '2023-11-08 17:34:46',
                'updated_at' => '2023-11-08 17:34:46',
            ),
            29 => 
            array (
                'id' => 30,
                'menu_id' => NULL,
                'parent_id' => 28,
                'parent_slug' => 'clients',
                'is_parent' => 0,
                'name' => 'Create Client',
                'title' => NULL,
                'slug' => 'create_client',
                'description' => NULL,
                'menu_order' => 12,
                'url' => 'client/create',
                'permissions' => 'client.clients.create',
                'icon' => 'far fa-circle',
                'module' => 'Client',
                'created_at' => '2023-11-08 17:34:46',
                'updated_at' => '2023-11-08 17:34:46',
            ),
            30 => 
            array (
                'id' => 31,
                'menu_id' => NULL,
                'parent_id' => NULL,
                'parent_slug' => '',
                'is_parent' => 1,
                'name' => 'Savings',
                'title' => NULL,
                'slug' => 'savings',
                'description' => NULL,
                'menu_order' => 25,
                'url' => 'savings',
                'permissions' => '',
                'icon' => 'fas fa-university',
                'module' => 'Savings',
                'created_at' => '2023-11-08 17:34:47',
                'updated_at' => '2023-11-08 17:34:47',
            ),
            31 => 
            array (
                'id' => 32,
                'menu_id' => NULL,
                'parent_id' => 31,
                'parent_slug' => 'savings',
                'is_parent' => 0,
                'name' => 'View Savings',
                'title' => NULL,
                'slug' => 'view_savings',
                'description' => NULL,
                'menu_order' => 26,
                'url' => 'savings',
                'permissions' => 'savings.savings.index',
                'icon' => 'far fa-circle',
                'module' => 'Savings',
                'created_at' => '2023-11-08 17:34:47',
                'updated_at' => '2023-11-08 17:34:47',
            ),
            32 => 
            array (
                'id' => 33,
                'menu_id' => NULL,
                'parent_id' => 31,
                'parent_slug' => 'savings',
                'is_parent' => 0,
                'name' => 'Create Savings',
                'title' => NULL,
                'slug' => 'create_savings',
                'description' => NULL,
                'menu_order' => 27,
                'url' => 'savings/create',
                'permissions' => 'savings.savings.create',
                'icon' => 'far fa-circle',
                'module' => 'Savings',
                'created_at' => '2023-11-08 17:34:47',
                'updated_at' => '2023-11-08 17:34:47',
            ),
            33 => 
            array (
                'id' => 34,
                'menu_id' => NULL,
                'parent_id' => 31,
                'parent_slug' => 'savings',
                'is_parent' => 0,
                'name' => 'Manage Products',
                'title' => NULL,
                'slug' => 'manage_products',
                'description' => NULL,
                'menu_order' => 28,
                'url' => 'savings/product',
                'permissions' => 'savings.savings.products.index',
                'icon' => 'far fa-circle',
                'module' => 'Savings',
                'created_at' => '2023-11-08 17:34:47',
                'updated_at' => '2023-11-08 17:34:47',
            ),
            34 => 
            array (
                'id' => 35,
                'menu_id' => NULL,
                'parent_id' => 31,
                'parent_slug' => 'savings',
                'is_parent' => 0,
                'name' => 'Manage Charges',
                'title' => NULL,
                'slug' => 'manage_charges',
                'description' => NULL,
                'menu_order' => 29,
                'url' => 'savings/charge',
                'permissions' => 'savings.savings.charges.index',
                'icon' => 'far fa-circle',
                'module' => 'Savings',
                'created_at' => '2023-11-08 17:34:47',
                'updated_at' => '2023-11-08 17:34:47',
            ),
            35 => 
            array (
                'id' => 36,
                'menu_id' => NULL,
                'parent_id' => NULL,
                'parent_slug' => '',
                'is_parent' => 1,
                'name' => 'Loans',
                'title' => NULL,
                'slug' => 'loans',
                'description' => NULL,
                'menu_order' => 18,
                'url' => 'loan',
                'permissions' => '',
                'icon' => 'fas fa-money-bill',
                'module' => 'Loan',
                'created_at' => '2023-11-08 17:34:49',
                'updated_at' => '2023-11-08 17:34:49',
            ),
            36 => 
            array (
                'id' => 37,
                'menu_id' => NULL,
                'parent_id' => 36,
                'parent_slug' => 'loans',
                'is_parent' => 0,
                'name' => 'View Loans',
                'title' => NULL,
                'slug' => 'view_loans',
                'description' => NULL,
                'menu_order' => 19,
                'url' => 'loan',
                'permissions' => 'loan.loans.index',
                'icon' => 'far fa-circle',
                'module' => 'Loan',
                'created_at' => '2023-11-08 17:34:49',
                'updated_at' => '2023-11-08 17:34:49',
            ),
            37 => 
            array (
                'id' => 38,
                'menu_id' => NULL,
                'parent_id' => 36,
                'parent_slug' => 'loans',
                'is_parent' => 0,
                'name' => 'View Applications',
                'title' => NULL,
                'slug' => 'view_applications',
                'description' => NULL,
                'menu_order' => 20,
                'url' => 'loan/application',
                'permissions' => 'loan.loans.index',
                'icon' => 'far fa-circle',
                'module' => 'Loan',
                'created_at' => '2023-11-08 17:34:49',
                'updated_at' => '2023-11-08 17:34:49',
            ),
            38 => 
            array (
                'id' => 39,
                'menu_id' => NULL,
                'parent_id' => 36,
                'parent_slug' => 'loans',
                'is_parent' => 0,
                'name' => 'Loan Repayments',
                'title' => NULL,
                'slug' => 'view_loan_repayments',
                'description' => NULL,
                'menu_order' => 21,
                'url' => 'loan/repayment',
                'permissions' => 'loan.loans.transactions.index',
                'icon' => 'far fa-circle',
                'module' => 'Loan',
                'created_at' => '2023-11-08 17:34:49',
                'updated_at' => '2023-11-08 17:34:49',
            ),
            39 => 
            array (
                'id' => 40,
                'menu_id' => NULL,
                'parent_id' => 36,
                'parent_slug' => 'loans',
                'is_parent' => 0,
                'name' => 'Create Loan',
                'title' => NULL,
                'slug' => 'create_loan',
                'description' => NULL,
                'menu_order' => 21,
                'url' => 'loan/create',
                'permissions' => 'loan.loans.create',
                'icon' => 'far fa-circle',
                'module' => 'Loan',
                'created_at' => '2023-11-08 17:34:49',
                'updated_at' => '2023-11-08 17:34:49',
            ),
            40 => 
            array (
                'id' => 41,
                'menu_id' => NULL,
                'parent_id' => 36,
                'parent_slug' => 'loans',
                'is_parent' => 0,
                'name' => 'Manage Products',
                'title' => NULL,
                'slug' => 'manage_products',
                'description' => NULL,
                'menu_order' => 22,
                'url' => 'loan/product',
                'permissions' => 'loan.loans.products.index',
                'icon' => 'far fa-circle',
                'module' => 'Loan',
                'created_at' => '2023-11-08 17:34:49',
                'updated_at' => '2023-11-08 17:34:49',
            ),
            41 => 
            array (
                'id' => 42,
                'menu_id' => NULL,
                'parent_id' => 36,
                'parent_slug' => 'loans',
                'is_parent' => 0,
                'name' => 'Manage Charges',
                'title' => NULL,
                'slug' => 'manage_charges',
                'description' => NULL,
                'menu_order' => 23,
                'url' => 'loan/charge',
                'permissions' => 'loan.loans.charges.index',
                'icon' => 'far fa-circle',
                'module' => 'Loan',
                'created_at' => '2023-11-08 17:34:49',
                'updated_at' => '2023-11-08 17:34:49',
            ),
            42 => 
            array (
                'id' => 43,
                'menu_id' => NULL,
                'parent_id' => 36,
                'parent_slug' => 'loans',
                'is_parent' => 0,
                'name' => 'Loan Calculator',
                'title' => NULL,
                'slug' => 'loan_calculator',
                'description' => NULL,
                'menu_order' => 24,
                'url' => 'loan/calculator',
                'permissions' => 'loan.loans.index',
                'icon' => 'far fa-circle',
                'module' => 'Loan',
                'created_at' => '2023-11-08 17:34:49',
                'updated_at' => '2023-11-08 17:34:49',
            ),
            43 => 
            array (
                'id' => 44,
                'menu_id' => NULL,
                'parent_id' => 36,
                'parent_slug' => 'loans',
                'is_parent' => 0,
                'name' => 'Loan Provisioning',
                'title' => NULL,
                'slug' => 'loan_provisioning',
                'description' => NULL,
                'menu_order' => 25,
                'url' => 'loan/loan_provisioning',
                'permissions' => 'loan.loans.loan_provisioning.index',
                'icon' => 'far fa-circle',
                'module' => 'Loan',
                'created_at' => '2023-11-08 17:34:49',
                'updated_at' => '2023-11-08 17:34:49',
            ),
            44 => 
            array (
                'id' => 45,
                'menu_id' => NULL,
                'parent_id' => NULL,
                'parent_slug' => 'report',
                'is_parent' => 1,
                'name' => 'Reports',
                'title' => NULL,
                'slug' => 'reports',
                'description' => NULL,
                'menu_order' => 20,
                'url' => 'report',
                'permissions' => 'reports.index',
                'icon' => 'fas fa-chart-bar',
                'module' => 'Report',
                'created_at' => '2023-11-08 17:34:49',
                'updated_at' => '2023-11-08 17:34:49',
            ),
            45 => 
            array (
                'id' => 46,
                'menu_id' => NULL,
                'parent_id' => NULL,
                'parent_slug' => '',
                'is_parent' => 1,
                'name' => 'Communication',
                'title' => NULL,
                'slug' => 'communication',
                'description' => NULL,
                'menu_order' => 13,
                'url' => 'communication',
                'permissions' => '',
                'icon' => 'fas fa-envelope',
                'module' => 'Communication',
                'created_at' => '2023-11-08 17:34:49',
                'updated_at' => '2023-11-08 17:34:49',
            ),
            46 => 
            array (
                'id' => 47,
                'menu_id' => NULL,
                'parent_id' => 46,
                'parent_slug' => 'communication',
                'is_parent' => 0,
                'name' => 'View Campaigns',
                'title' => NULL,
                'slug' => 'view_campaigns',
                'description' => NULL,
                'menu_order' => 14,
                'url' => 'communication/campaign',
                'permissions' => 'communication.campaigns.index',
                'icon' => 'far fa-circle',
                'module' => 'Communication',
                'created_at' => '2023-11-08 17:34:49',
                'updated_at' => '2023-11-08 17:34:49',
            ),
            47 => 
            array (
                'id' => 48,
                'menu_id' => NULL,
                'parent_id' => 46,
                'parent_slug' => 'communication',
                'is_parent' => 0,
                'name' => 'Create Campaign',
                'title' => NULL,
                'slug' => 'create_campaign',
                'description' => NULL,
                'menu_order' => 15,
                'url' => 'communication/campaign/create',
                'permissions' => 'communication.campaigns.create',
                'icon' => 'far fa-circle',
                'module' => 'Communication',
                'created_at' => '2023-11-08 17:34:49',
                'updated_at' => '2023-11-08 17:34:49',
            ),
            48 => 
            array (
                'id' => 49,
                'menu_id' => NULL,
                'parent_id' => 46,
                'parent_slug' => 'communication',
                'is_parent' => 0,
                'name' => 'View Logs',
                'title' => NULL,
                'slug' => 'view_logs',
                'description' => NULL,
                'menu_order' => 16,
                'url' => 'communication/log',
                'permissions' => 'communication.logs.index',
                'icon' => 'far fa-circle',
                'module' => 'Communication',
                'created_at' => '2023-11-08 17:34:49',
                'updated_at' => '2023-11-08 17:34:49',
            ),
            49 => 
            array (
                'id' => 50,
                'menu_id' => NULL,
                'parent_id' => 46,
                'parent_slug' => 'communication',
                'is_parent' => 0,
                'name' => 'Manage SMS Gateways',
                'title' => NULL,
                'slug' => 'manage_sms_gateways',
                'description' => NULL,
                'menu_order' => 17,
                'url' => 'communication/sms_gateway',
                'permissions' => 'communication.sms_gateways.index',
                'icon' => 'far fa-circle',
                'module' => 'Communication',
                'created_at' => '2023-11-08 17:34:49',
                'updated_at' => '2023-11-08 17:34:49',
            ),
            50 => 
            array (
                'id' => 51,
                'menu_id' => NULL,
                'parent_id' => NULL,
                'parent_slug' => '',
                'is_parent' => 1,
                'name' => 'Payroll',
                'title' => NULL,
                'slug' => 'payroll',
                'description' => NULL,
                'menu_order' => 10,
                'url' => 'payroll',
                'permissions' => 'payroll.payroll.index',
                'icon' => 'fab fa-paypal',
                'module' => 'Payroll',
                'created_at' => '2023-11-08 17:34:50',
                'updated_at' => '2023-11-08 17:34:50',
            ),
            51 => 
            array (
                'id' => 52,
                'menu_id' => NULL,
                'parent_id' => 51,
                'parent_slug' => 'payroll',
                'is_parent' => 0,
                'name' => 'View Payroll',
                'title' => NULL,
                'slug' => 'view_payroll',
                'description' => NULL,
                'menu_order' => 11,
                'url' => 'payroll',
                'permissions' => 'payroll.payroll.index',
                'icon' => 'far fa-circle',
                'module' => 'Payroll',
                'created_at' => '2023-11-08 17:34:50',
                'updated_at' => '2023-11-08 17:34:50',
            ),
            52 => 
            array (
                'id' => 53,
                'menu_id' => NULL,
                'parent_id' => 51,
                'parent_slug' => 'payroll',
                'is_parent' => 0,
                'name' => 'Create Payroll',
                'title' => NULL,
                'slug' => 'create_payroll',
                'description' => NULL,
                'menu_order' => 12,
                'url' => 'payroll/create',
                'permissions' => 'payroll.payroll.create',
                'icon' => 'far fa-circle',
                'module' => 'Payroll',
                'created_at' => '2023-11-08 17:34:50',
                'updated_at' => '2023-11-08 17:34:50',
            ),
            53 => 
            array (
                'id' => 54,
                'menu_id' => NULL,
                'parent_id' => 51,
                'parent_slug' => 'payroll',
                'is_parent' => 0,
                'name' => 'Manage Payroll Items',
                'title' => NULL,
                'slug' => 'manage_payroll_items',
                'description' => NULL,
                'menu_order' => 12,
                'url' => 'payroll/item',
                'permissions' => 'payroll.payroll.items.index',
                'icon' => 'far fa-circle',
                'module' => 'Payroll',
                'created_at' => '2023-11-08 17:34:50',
                'updated_at' => '2023-11-08 17:34:50',
            ),
            54 => 
            array (
                'id' => 55,
                'menu_id' => NULL,
                'parent_id' => 51,
                'parent_slug' => 'payroll',
                'is_parent' => 0,
                'name' => 'Manage Payroll Templates',
                'title' => NULL,
                'slug' => 'manage_payroll_templates',
                'description' => NULL,
                'menu_order' => 12,
                'url' => 'payroll/template',
                'permissions' => 'payroll.payroll.templates.index',
                'icon' => 'far fa-circle',
                'module' => 'Payroll',
                'created_at' => '2023-11-08 17:34:50',
                'updated_at' => '2023-11-08 17:34:50',
            ),
            55 => 
            array (
                'id' => 56,
                'menu_id' => NULL,
                'parent_id' => NULL,
                'parent_slug' => '',
                'is_parent' => 1,
                'name' => 'Custom Fields',
                'title' => NULL,
                'slug' => 'custom_fields',
                'description' => NULL,
                'menu_order' => 25,
                'url' => 'custom_field',
                'permissions' => '',
                'icon' => 'fas fa-list',
                'module' => 'CustomField',
                'created_at' => '2023-11-08 17:34:50',
                'updated_at' => '2023-11-08 17:34:50',
            ),
            56 => 
            array (
                'id' => 57,
                'menu_id' => NULL,
                'parent_id' => 56,
                'parent_slug' => 'custom_fields',
                'is_parent' => 0,
                'name' => 'View Custom Fields',
                'title' => NULL,
                'slug' => 'view_custom_fields',
                'description' => NULL,
                'menu_order' => 26,
                'url' => 'custom_field',
                'permissions' => 'customfield.custom_fields.index',
                'icon' => 'far fa-circle',
                'module' => 'Savings',
                'created_at' => '2023-11-08 17:34:50',
                'updated_at' => '2023-11-08 17:34:50',
            ),
            57 => 
            array (
                'id' => 58,
                'menu_id' => NULL,
                'parent_id' => 56,
                'parent_slug' => 'custom_fields',
                'is_parent' => 0,
                'name' => 'Create Custom Field',
                'title' => NULL,
                'slug' => 'create_custom_fields',
                'description' => NULL,
                'menu_order' => 27,
                'url' => 'custom_field/create',
                'permissions' => 'customfield.custom_fields.create',
                'icon' => 'far fa-circle',
                'module' => 'Savings',
                'created_at' => '2023-11-08 17:34:50',
                'updated_at' => '2023-11-08 17:34:50',
            ),
            58 => 
            array (
                'id' => 59,
                'menu_id' => NULL,
                'parent_id' => NULL,
                'parent_slug' => '',
                'is_parent' => 1,
                'name' => 'Expenses',
                'title' => NULL,
                'slug' => 'expenses',
                'description' => NULL,
                'menu_order' => 20,
                'url' => 'expense',
                'permissions' => 'expense.expenses.index',
                'icon' => 'fas fa-share',
                'module' => 'Expense',
                'created_at' => '2023-11-08 17:34:50',
                'updated_at' => '2023-11-08 17:34:50',
            ),
            59 => 
            array (
                'id' => 60,
                'menu_id' => NULL,
                'parent_id' => 59,
                'parent_slug' => 'expenses',
                'is_parent' => 0,
                'name' => 'View Expenses',
                'title' => NULL,
                'slug' => 'view_expenses',
                'description' => NULL,
                'menu_order' => 0,
                'url' => 'expense',
                'permissions' => 'expense.expenses.index',
                'icon' => 'far fa-circle',
                'module' => 'Expense',
                'created_at' => '2023-11-08 17:34:50',
                'updated_at' => '2023-11-08 17:34:50',
            ),
            60 => 
            array (
                'id' => 61,
                'menu_id' => NULL,
                'parent_id' => 59,
                'parent_slug' => 'expenses',
                'is_parent' => 0,
                'name' => 'Create Expense',
                'title' => NULL,
                'slug' => 'create_expense',
                'description' => NULL,
                'menu_order' => 1,
                'url' => 'expense/create',
                'permissions' => 'expense.expenses.create',
                'icon' => 'far fa-circle',
                'module' => 'Expense',
                'created_at' => '2023-11-08 17:34:50',
                'updated_at' => '2023-11-08 17:34:50',
            ),
            61 => 
            array (
                'id' => 62,
                'menu_id' => NULL,
                'parent_id' => 59,
                'parent_slug' => 'expenses',
                'is_parent' => 0,
                'name' => 'Manage Expense Types',
                'title' => NULL,
                'slug' => 'manage_expense_types',
                'description' => NULL,
                'menu_order' => 2,
                'url' => 'expense/type',
                'permissions' => 'expense.expenses.types.index',
                'icon' => 'far fa-circle',
                'module' => 'Expense',
                'created_at' => '2023-11-08 17:34:50',
                'updated_at' => '2023-11-08 17:34:50',
            ),
            62 => 
            array (
                'id' => 63,
                'menu_id' => NULL,
                'parent_id' => NULL,
                'parent_slug' => '',
                'is_parent' => 1,
                'name' => 'Income',
                'title' => NULL,
                'slug' => 'income',
                'description' => NULL,
                'menu_order' => 25,
                'url' => 'income',
                'permissions' => 'income.income.index',
                'icon' => 'fas fa-money-bill',
                'module' => 'Income',
                'created_at' => '2023-11-08 17:34:51',
                'updated_at' => '2023-11-08 17:34:51',
            ),
            63 => 
            array (
                'id' => 64,
                'menu_id' => NULL,
                'parent_id' => 63,
                'parent_slug' => 'income',
                'is_parent' => 0,
                'name' => 'View Income',
                'title' => NULL,
                'slug' => 'view_assets',
                'description' => NULL,
                'menu_order' => 7,
                'url' => 'income',
                'permissions' => 'income.income.index',
                'icon' => 'far fa-circle',
                'module' => 'Income',
                'created_at' => '2023-11-08 17:34:51',
                'updated_at' => '2023-11-08 17:34:51',
            ),
            64 => 
            array (
                'id' => 65,
                'menu_id' => NULL,
                'parent_id' => 63,
                'parent_slug' => 'income',
                'is_parent' => 0,
                'name' => 'Create Income',
                'title' => NULL,
                'slug' => 'create_asset',
                'description' => NULL,
                'menu_order' => 8,
                'url' => 'income/create',
                'permissions' => 'income.income.create',
                'icon' => 'far fa-circle',
                'module' => 'Income',
                'created_at' => '2023-11-08 17:34:51',
                'updated_at' => '2023-11-08 17:34:51',
            ),
            65 => 
            array (
                'id' => 66,
                'menu_id' => NULL,
                'parent_id' => 63,
                'parent_slug' => 'income',
                'is_parent' => 0,
                'name' => 'Manage Income Types',
                'title' => NULL,
                'slug' => 'manage_asset_types',
                'description' => NULL,
                'menu_order' => 9,
                'url' => 'income/type',
                'permissions' => 'income.income.types.index',
                'icon' => 'far fa-circle',
                'module' => 'Income',
                'created_at' => '2023-11-08 17:34:51',
                'updated_at' => '2023-11-08 17:34:51',
            ),
            66 => 
            array (
                'id' => 67,
                'menu_id' => NULL,
                'parent_id' => 1,
                'parent_slug' => 'settings',
                'is_parent' => 0,
                'name' => 'System Upgrade',
                'title' => NULL,
                'slug' => 'system_upgrade',
                'description' => NULL,
                'menu_order' => 40,
                'url' => 'upgrade',
                'permissions' => 'upgrade.upgrades.index',
                'icon' => 'fa fa-circle-o',
                'module' => 'Setting',
                'created_at' => '2023-11-08 17:34:51',
                'updated_at' => '2023-11-08 17:34:51',
            ),
            67 => 
            array (
                'id' => 68,
                'menu_id' => NULL,
                'parent_id' => NULL,
                'parent_slug' => '',
                'is_parent' => 1,
                'name' => 'Shares',
                'title' => NULL,
                'slug' => 'shares',
                'description' => NULL,
                'menu_order' => 30,
                'url' => 'share',
                'permissions' => 'share.shares.index',
                'icon' => 'fas fa-database',
                'module' => 'Share',
                'created_at' => '2023-11-08 17:34:52',
                'updated_at' => '2023-11-08 17:34:52',
            ),
            68 => 
            array (
                'id' => 69,
                'menu_id' => NULL,
                'parent_id' => 68,
                'parent_slug' => 'shares',
                'is_parent' => 0,
                'name' => 'View Shares',
                'title' => NULL,
                'slug' => 'view_shares',
                'description' => NULL,
                'menu_order' => 1,
                'url' => 'share',
                'permissions' => 'share.shares.index',
                'icon' => 'far fa-circle',
                'module' => 'Share',
                'created_at' => '2023-11-08 17:34:52',
                'updated_at' => '2023-11-08 17:34:52',
            ),
            69 => 
            array (
                'id' => 70,
                'menu_id' => NULL,
                'parent_id' => 68,
                'parent_slug' => 'shares',
                'is_parent' => 0,
                'name' => 'Create Share',
                'title' => NULL,
                'slug' => 'create_share',
                'description' => NULL,
                'menu_order' => 2,
                'url' => 'share/create',
                'permissions' => 'share.shares.create',
                'icon' => 'far fa-circle',
                'module' => 'Share',
                'created_at' => '2023-11-08 17:34:52',
                'updated_at' => '2023-11-08 17:34:52',
            ),
            70 => 
            array (
                'id' => 71,
                'menu_id' => NULL,
                'parent_id' => 68,
                'parent_slug' => 'shares',
                'is_parent' => 0,
                'name' => 'Manage Products',
                'title' => NULL,
                'slug' => 'manage_share_products',
                'description' => NULL,
                'menu_order' => 3,
                'url' => 'share/product',
                'permissions' => 'share.shares.products.index',
                'icon' => 'far fa-circle',
                'module' => 'Share',
                'created_at' => '2023-11-08 17:34:52',
                'updated_at' => '2023-11-08 17:34:52',
            ),
            71 => 
            array (
                'id' => 72,
                'menu_id' => NULL,
                'parent_id' => 68,
                'parent_slug' => 'shares',
                'is_parent' => 0,
                'name' => 'Manage Charges',
                'title' => NULL,
                'slug' => 'manage_share_charges',
                'description' => NULL,
                'menu_order' => 3,
                'url' => 'share/charge',
                'permissions' => 'share.shares.charges.index',
                'icon' => 'far fa-circle',
                'module' => 'Share',
                'created_at' => '2023-11-08 17:34:52',
                'updated_at' => '2023-11-08 17:34:52',
            ),
            72 => 
            array (
                'id' => 73,
                'menu_id' => NULL,
                'parent_id' => NULL,
                'parent_slug' => '',
                'is_parent' => 1,
                'name' => 'Activity Logs',
                'title' => NULL,
                'slug' => 'activity_log',
                'description' => NULL,
                'menu_order' => 60,
                'url' => 'activity_log',
                'permissions' => 'activitylog.activity_logs.index',
                'icon' => 'fa fa-database',
                'module' => 'Activitylog',
                'created_at' => '2023-11-08 17:34:52',
                'updated_at' => '2023-11-08 17:34:52',
            ),
        ));
        
        
    }
}