<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class SettingsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('settings')->delete();
        
        \DB::table('settings')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Company Name',
                'setting_key' => 'core.company_name',
                'module' => 'Core',
                'setting_value' => 'Ultimate Loan Manager',
                'order' => NULL,
                'category' => 'general',
                'type' => 'text',
                'options' => '',
                'rules' => '',
                'class' => '',
                'required' => 1,
                'db_columns' => '',
                'info' => NULL,
                'displayed' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Company Address',
                'setting_key' => 'core.company_address',
                'module' => 'Core',
                'setting_value' => '',
                'order' => NULL,
                'category' => 'general',
                'type' => 'textarea',
                'options' => '',
                'rules' => '',
                'class' => '',
                'required' => 0,
                'db_columns' => '',
                'info' => NULL,
                'displayed' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Company Country',
                'setting_key' => 'core.company_country',
                'module' => 'Core',
                'setting_value' => '',
                'order' => NULL,
                'category' => 'general',
                'type' => 'select_db',
                'options' => 'countries',
                'rules' => '',
                'class' => 'select2',
                'required' => 0,
                'db_columns' => 'id,name',
                'info' => NULL,
                'displayed' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Timezone',
                'setting_key' => 'core.timezone',
                'module' => 'Core',
                'setting_value' => '1',
                'order' => NULL,
                'category' => 'general',
                'type' => 'select_db',
                'options' => 'timezones',
                'rules' => '',
                'class' => 'select2',
                'required' => 1,
                'db_columns' => 'id,zone_name',
                'info' => NULL,
                'displayed' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'System Version',
                'setting_key' => 'core.system_version',
                'module' => 'Core',
                'setting_value' => '3.0',
                'order' => NULL,
                'category' => 'update',
                'type' => 'info',
                'options' => '',
                'rules' => '',
                'class' => '',
                'required' => 1,
                'db_columns' => '',
                'info' => NULL,
                'displayed' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Company Email',
                'setting_key' => 'core.company_email',
                'module' => 'Core',
                'setting_value' => 'nonreply@company.com',
                'order' => NULL,
                'category' => 'general',
                'type' => 'text',
                'options' => '',
                'rules' => '',
                'class' => '',
                'required' => 1,
                'db_columns' => '',
                'info' => NULL,
                'displayed' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Company Logo',
                'setting_key' => 'core.company_logo',
                'module' => 'Core',
                'setting_value' => '',
                'order' => NULL,
                'category' => 'general',
                'type' => 'file',
                'options' => 'jpeg,jpg,bmp,png',
                'rules' => 'nullable|file|mimes:jpeg,jpg,bmp,png',
                'class' => '',
                'required' => 0,
                'db_columns' => '',
                'info' => NULL,
                'displayed' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Site Online',
                'setting_key' => 'core.site_online',
                'module' => 'Core',
                'setting_value' => 'yes',
                'order' => NULL,
                'category' => 'system',
                'type' => 'select',
                'options' => 'yes,no',
                'rules' => '',
                'class' => '',
                'required' => 1,
                'db_columns' => '',
                'info' => NULL,
                'displayed' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Console Last Run',
                'setting_key' => 'core.console_last_run',
                'module' => 'Core',
                'setting_value' => '',
                'order' => NULL,
                'category' => 'system',
                'type' => 'info',
                'options' => '',
                'rules' => '',
                'class' => '',
                'required' => 1,
                'db_columns' => '',
                'info' => NULL,
                'displayed' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Update Url',
                'setting_key' => 'core.update_url',
                'module' => 'Core',
                'setting_value' => 'http://webstudio.co.zw/ulm/update',
                'order' => NULL,
                'category' => 'general',
                'type' => 'info',
                'options' => '',
                'rules' => '',
                'class' => '',
                'required' => 1,
                'db_columns' => '',
                'info' => NULL,
                'displayed' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Auto Download Update',
                'setting_key' => 'core.auto_download_update',
                'module' => 'Core',
                'setting_value' => 'no',
                'order' => NULL,
                'category' => 'system',
                'type' => 'select',
                'options' => 'yes,no',
                'rules' => '',
                'class' => '',
                'required' => 1,
                'db_columns' => '',
                'info' => NULL,
                'displayed' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Update last checked',
                'setting_key' => 'core.update_last_checked',
                'module' => 'Core',
                'setting_value' => '',
                'order' => NULL,
                'category' => 'system',
                'type' => 'info',
                'options' => '',
                'rules' => '',
                'class' => '',
                'required' => 1,
                'db_columns' => '',
                'info' => NULL,
                'displayed' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Extra Javascript',
                'setting_key' => 'core.extra_javascript',
                'module' => 'Core',
                'setting_value' => '',
                'order' => NULL,
                'category' => 'system',
                'type' => 'textarea',
                'options' => '',
                'rules' => '',
                'class' => '',
                'required' => 0,
                'db_columns' => '',
                'info' => NULL,
                'displayed' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Extra Styles',
                'setting_key' => 'core.extra_styles',
                'module' => 'Core',
                'setting_value' => '',
                'order' => NULL,
                'category' => 'system',
                'type' => 'textarea',
                'options' => '',
                'rules' => '',
                'class' => '',
                'required' => 0,
                'db_columns' => '',
                'info' => NULL,
                'displayed' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Demo Mode',
                'setting_key' => 'core.demo_mode',
                'module' => 'Core',
                'setting_value' => 'no',
                'order' => NULL,
                'category' => 'system',
                'type' => 'select',
                'options' => 'yes,no',
                'rules' => '',
                'class' => '',
                'required' => 1,
                'db_columns' => '',
                'info' => NULL,
                'displayed' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Purchase Code',
                'setting_key' => 'core.purchase_code',
                'module' => 'Core',
                'setting_value' => '',
                'order' => NULL,
                'category' => 'system',
                'type' => 'text',
                'options' => '',
                'rules' => '',
                'class' => '',
                'required' => 0,
                'db_columns' => '',
                'info' => NULL,
                'displayed' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Purchase Code Type',
                'setting_key' => 'core.purchase_code_type',
                'module' => 'Core',
                'setting_value' => '',
                'order' => NULL,
                'category' => 'system',
                'type' => 'text',
                'options' => '',
                'rules' => '',
                'class' => '',
                'required' => 0,
                'db_columns' => '',
                'info' => NULL,
                'displayed' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Installed IP Address',
                'setting_key' => 'core.installed_ip_address',
                'module' => 'Core',
                'setting_value' => '',
                'order' => NULL,
                'category' => 'system',
                'type' => 'text',
                'options' => '',
                'rules' => '',
                'class' => '',
                'required' => 0,
                'db_columns' => '',
                'info' => NULL,
                'displayed' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'License Details',
                'setting_key' => 'core.license_details',
                'module' => 'Core',
                'setting_value' => '',
                'order' => NULL,
                'category' => 'system',
                'type' => 'text',
                'options' => '',
                'rules' => '',
                'class' => '',
                'required' => 0,
                'db_columns' => '',
                'info' => NULL,
                'displayed' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'Active Theme',
                'setting_key' => 'core.active_theme',
                'module' => 'Core',
                'setting_value' => 'AdminLTE',
                'order' => NULL,
                'category' => 'system',
                'type' => 'text',
                'options' => '',
                'rules' => '',
                'class' => '',
                'required' => 0,
                'db_columns' => '',
                'info' => NULL,
                'displayed' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'Registration Enabled',
                'setting_key' => 'user.enable_registration',
                'module' => 'User',
                'setting_value' => 'no',
                'order' => NULL,
                'category' => 'system',
                'type' => 'select',
                'options' => 'yes,no',
                'rules' => NULL,
                'class' => '',
                'required' => 1,
                'db_columns' => '',
                'info' => NULL,
                'displayed' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'Enable Google recaptcha',
                'setting_key' => 'user.enable_google_recaptcha',
                'module' => 'User',
                'setting_value' => 'no',
                'order' => NULL,
                'category' => 'system',
                'type' => 'select',
                'options' => 'yes,no',
                'rules' => NULL,
                'class' => '',
                'required' => 1,
                'db_columns' => '',
                'info' => NULL,
                'displayed' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'Google recaptcha site key',
                'setting_key' => 'user.google_recaptcha_site_key',
                'module' => 'User',
                'setting_value' => '',
                'order' => NULL,
                'category' => 'system',
                'type' => 'text',
                'options' => '',
                'rules' => NULL,
                'class' => '',
                'required' => 0,
                'db_columns' => '',
                'info' => NULL,
                'displayed' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'Google recaptcha secret key',
                'setting_key' => 'user.google_recaptcha_secret_key',
                'module' => 'User',
                'setting_value' => '',
                'order' => NULL,
                'category' => 'system',
                'type' => 'text',
                'options' => '',
                'rules' => NULL,
                'class' => '',
                'required' => 0,
                'db_columns' => '',
                'info' => NULL,
                'displayed' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'Client In-Active Days',
                'setting_key' => 'client.inactive_days',
                'module' => 'Client',
                'setting_value' => '',
                'order' => NULL,
                'category' => 'general',
                'type' => 'text',
                'options' => '',
                'rules' => '',
                'class' => '',
                'required' => 0,
                'db_columns' => '',
                'info' => NULL,
                'displayed' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'Client Reference Prefix',
                'setting_key' => 'client.reference_prefix',
                'module' => 'Client',
                'setting_value' => 'CL',
                'order' => NULL,
                'category' => 'system',
                'type' => 'text',
                'options' => '',
                'rules' => '',
                'class' => '',
                'required' => 0,
                'db_columns' => '',
                'info' => NULL,
                'displayed' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'Client Reference Format',
                'setting_key' => 'client.reference_format',
                'module' => 'Client',
            'setting_value' => 'YEAR/Sequence Number (SL/2014/001)',
                'order' => NULL,
                'category' => 'system',
                'type' => 'select',
            'options' => 'YEAR/Sequence Number (SL/2014/001),YEAR/MONTH/Sequence Number (SL/2014/08/001),Sequence Number,Random Number,Branch Sequence Number',
                'rules' => '',
                'class' => '',
                'required' => 1,
                'db_columns' => '',
                'info' => NULL,
                'displayed' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'Savings Reference Prefix',
                'setting_key' => 'savings.reference_prefix',
                'module' => 'Savings',
                'setting_value' => '',
                'order' => NULL,
                'category' => 'system',
                'type' => 'text',
                'options' => '',
                'rules' => '',
                'class' => '',
                'required' => 0,
                'db_columns' => '',
                'info' => NULL,
                'displayed' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'Savings Reference Format',
                'setting_key' => 'savings.reference_format',
                'module' => 'Savings',
            'setting_value' => 'YEAR/Sequence Number (SL/2014/001)',
                'order' => NULL,
                'category' => 'system',
                'type' => 'select',
            'options' => 'YEAR/Sequence Number (SL/2014/001),YEAR/MONTH/Sequence Number (SL/2014/08/001),Sequence Number,Random Number,Branch Product Sequence Number',
                'rules' => '',
                'class' => '',
                'required' => 1,
                'db_columns' => '',
                'info' => NULL,
                'displayed' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'Loan Reference Prefix',
                'setting_key' => 'loan.reference_prefix',
                'module' => 'Loan',
                'setting_value' => 'L',
                'order' => NULL,
                'category' => 'system',
                'type' => 'text',
                'options' => '',
                'rules' => '',
                'class' => '',
                'required' => 0,
                'db_columns' => '',
                'info' => NULL,
                'displayed' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'Loan Reference Format',
                'setting_key' => 'loan.reference_format',
                'module' => 'Loan',
            'setting_value' => 'YEAR/Sequence Number (SL/2014/001)',
                'order' => NULL,
                'category' => 'system',
                'type' => 'select',
            'options' => 'YEAR/Sequence Number (SL/2014/001),YEAR/MONTH/Sequence Number (SL/2014/08/001),Sequence Number,Random Number,Branch Product Sequence Number',
                'rules' => '',
                'class' => '',
                'required' => 1,
                'db_columns' => '',
                'info' => NULL,
                'displayed' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'SMS Enabled',
                'setting_key' => 'communication.sms_enabled',
                'module' => 'Communication',
                'setting_value' => 'no',
                'order' => NULL,
                'category' => 'sms',
                'type' => 'select',
                'options' => 'yes,no',
                'rules' => '',
                'class' => '',
                'required' => 1,
                'db_columns' => '',
                'info' => NULL,
                'displayed' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'Active SMS Gateway',
                'setting_key' => 'communication.active_sms_gateway',
                'module' => 'Communication',
                'setting_value' => '1',
                'order' => NULL,
                'category' => 'sms',
                'type' => 'select_db',
                'options' => 'sms_gateways',
                'rules' => '',
                'class' => 'select2',
                'required' => 0,
                'db_columns' => 'id,name',
                'info' => NULL,
                'displayed' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}